import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "warn",
    pedantic: "off",
    style: "off",
    restriction: "off",
  },
  options: {
    reportUnusedDisableDirectives: "error",
  },
  ignorePatterns: [
    "node_modules/**",
    ".next/**",
    "out/**",
    "coverage/**",
    "*.d.ts",
    "tools/**",
    "**/*.test.ts",
    "**/*.test.tsx",
  ],
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
  ],
  rules: {
    "eslint/no-unused-vars": "warn",
    "unicorn/no-empty-file": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/require-post-message-target-origin": "off",
    "eslint/no-underscore-dangle": "off",
    "eslint/no-dupe-else-if": "warn",
    "eslint/no-await-in-loop": "warn",
    "eslint/no-useless-catch": "warn",
    "eslint/preserve-caught-error": "warn",
    "eslint/no-shadow": "warn",
    "anti-slop/no-chained-type-assertions": "warn",
    "anti-slop/no-conditional-empty-object-spread": "warn",
    "anti-slop/no-known-value-widening": "warn",
    "anti-slop/no-module-mocking": "warn",
    "anti-slop/no-object-parameters": "warn",
    "anti-slop/no-reflect-apply": "warn",
    "anti-slop/no-reflect-get": "warn",
    "anti-slop/no-runtime-typeof": ["warn", { allowInTypeGuards: true }],
    "anti-slop/no-shape-in-symbol-names": "off",
    "anti-slop/no-unknown-parameters": "off",
    "anti-slop/no-unknown-returns": "warn",
    "anti-slop/no-unknown-type-aliases": "warn",
    "anti-slop/no-unsafe-dictionary-type": "warn",
    "anti-slop/no-widen-then-assert": "warn",
    "anti-slop/require-safety-comment-for-type-assertion": "warn",
  },
});